### ISSUE TITLE
SQLAlchemy Broken Pipe Error

### ISSUE THREAD

**Issue by CopperBadger** [FursuiterNET/Fursuiter#6]
Got this error while working on the site, server became unresponsive as a result. Is there a way to avoid this?

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/distill/application.py", line 54, in __call__
    resp = self._request(env, req)
  File "/usr/local/lib/python2.7/dist-packages/distill/application.py", line 90, in _request
    self._do_before(req, resp)
  File "/usr/local/lib/python2.7/dist-packages/distill/application.py", line 122, in _do_before
    f(req, resp)
  File "/home/copper/Development/Fursuiter/Fursuiter/authentication/session.py", line 23, in validate_session
    user = Session().query(User).filter(User.username == request.session['username']).scalar()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2426, in scalar
    ret = self.one()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2395, in one
    ret = list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2451, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2442, in _connection_from_session
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 854, in connection
    close_with_result=close_with_result)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 858, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 322, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1798, in contextual_connect
    self.pool.connect(),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 338, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 644, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 959, in _do_get
    (self.size(), self.overflow(), self._timeout))
TimeoutError: QueuePool limit of size 12 overflow 10 reached, connection timed out, timeout 30
127.0.0.1 - - [14/Feb/2015 17:26:51] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42618)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by rechner** [comment]
`TimeoutError: QueuePool limit of size 12 overflow 10 reached, connection timed out, timeout 30
127.0.0.1 - - [14/Feb/2015 17:26:51] "GET / HTTP/1.1" 500 59`

means: Pool size: 12 + 10 overflow = 22 connections all trying to access the database pool all at once. 10 are waiting on a connection.  Seems we're using up all the connection pool resources for some reason.  We might not be cleaning up connections to the database everywhere we should be, or using improper request context.

Try increasing SQL Alchemy's `max_pool_size` or `pool_size` instance parameter as a quick fix.
